o errors     - implemented Has() function     - Error() now de-duplicates error string parts     * for example, instead of:
	    error: foo: foo: bar

	Error() will now return:

	    error: foo: bar